/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GridUpdateRouteImport } from './routes/grid-update'
import { Route as GridServerRouteImport } from './routes/grid-server'
import { Route as GridSaveRouteImport } from './routes/grid-save'
import { Route as GridInlineRouteImport } from './routes/grid-inline'
import { Route as GridBatchRouteImport } from './routes/grid-batch'
import { Route as GridApiRouteImport } from './routes/grid-api'
import { Route as GridAddDeleteRouteImport } from './routes/grid-add-delete'
import { Route as GridRouteImport } from './routes/grid'
import { Route as IndexRouteImport } from './routes/index'

const GridUpdateRoute = GridUpdateRouteImport.update({
  id: '/grid-update',
  path: '/grid-update',
  getParentRoute: () => rootRouteImport,
} as any)
const GridServerRoute = GridServerRouteImport.update({
  id: '/grid-server',
  path: '/grid-server',
  getParentRoute: () => rootRouteImport,
} as any)
const GridSaveRoute = GridSaveRouteImport.update({
  id: '/grid-save',
  path: '/grid-save',
  getParentRoute: () => rootRouteImport,
} as any)
const GridInlineRoute = GridInlineRouteImport.update({
  id: '/grid-inline',
  path: '/grid-inline',
  getParentRoute: () => rootRouteImport,
} as any)
const GridBatchRoute = GridBatchRouteImport.update({
  id: '/grid-batch',
  path: '/grid-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const GridApiRoute = GridApiRouteImport.update({
  id: '/grid-api',
  path: '/grid-api',
  getParentRoute: () => rootRouteImport,
} as any)
const GridAddDeleteRoute = GridAddDeleteRouteImport.update({
  id: '/grid-add-delete',
  path: '/grid-add-delete',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grid': typeof GridRoute
  '/grid-add-delete': typeof GridAddDeleteRoute
  '/grid-api': typeof GridApiRoute
  '/grid-batch': typeof GridBatchRoute
  '/grid-inline': typeof GridInlineRoute
  '/grid-save': typeof GridSaveRoute
  '/grid-server': typeof GridServerRoute
  '/grid-update': typeof GridUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grid': typeof GridRoute
  '/grid-add-delete': typeof GridAddDeleteRoute
  '/grid-api': typeof GridApiRoute
  '/grid-batch': typeof GridBatchRoute
  '/grid-inline': typeof GridInlineRoute
  '/grid-save': typeof GridSaveRoute
  '/grid-server': typeof GridServerRoute
  '/grid-update': typeof GridUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grid': typeof GridRoute
  '/grid-add-delete': typeof GridAddDeleteRoute
  '/grid-api': typeof GridApiRoute
  '/grid-batch': typeof GridBatchRoute
  '/grid-inline': typeof GridInlineRoute
  '/grid-save': typeof GridSaveRoute
  '/grid-server': typeof GridServerRoute
  '/grid-update': typeof GridUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grid'
    | '/grid-add-delete'
    | '/grid-api'
    | '/grid-batch'
    | '/grid-inline'
    | '/grid-save'
    | '/grid-server'
    | '/grid-update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grid'
    | '/grid-add-delete'
    | '/grid-api'
    | '/grid-batch'
    | '/grid-inline'
    | '/grid-save'
    | '/grid-server'
    | '/grid-update'
  id:
    | '__root__'
    | '/'
    | '/grid'
    | '/grid-add-delete'
    | '/grid-api'
    | '/grid-batch'
    | '/grid-inline'
    | '/grid-save'
    | '/grid-server'
    | '/grid-update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GridRoute: typeof GridRoute
  GridAddDeleteRoute: typeof GridAddDeleteRoute
  GridApiRoute: typeof GridApiRoute
  GridBatchRoute: typeof GridBatchRoute
  GridInlineRoute: typeof GridInlineRoute
  GridSaveRoute: typeof GridSaveRoute
  GridServerRoute: typeof GridServerRoute
  GridUpdateRoute: typeof GridUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/grid-update': {
      id: '/grid-update'
      path: '/grid-update'
      fullPath: '/grid-update'
      preLoaderRoute: typeof GridUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-server': {
      id: '/grid-server'
      path: '/grid-server'
      fullPath: '/grid-server'
      preLoaderRoute: typeof GridServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-save': {
      id: '/grid-save'
      path: '/grid-save'
      fullPath: '/grid-save'
      preLoaderRoute: typeof GridSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-inline': {
      id: '/grid-inline'
      path: '/grid-inline'
      fullPath: '/grid-inline'
      preLoaderRoute: typeof GridInlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-batch': {
      id: '/grid-batch'
      path: '/grid-batch'
      fullPath: '/grid-batch'
      preLoaderRoute: typeof GridBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-api': {
      id: '/grid-api'
      path: '/grid-api'
      fullPath: '/grid-api'
      preLoaderRoute: typeof GridApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-add-delete': {
      id: '/grid-add-delete'
      path: '/grid-add-delete'
      fullPath: '/grid-add-delete'
      preLoaderRoute: typeof GridAddDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GridRoute: GridRoute,
  GridAddDeleteRoute: GridAddDeleteRoute,
  GridApiRoute: GridApiRoute,
  GridBatchRoute: GridBatchRoute,
  GridInlineRoute: GridInlineRoute,
  GridSaveRoute: GridSaveRoute,
  GridServerRoute: GridServerRoute,
  GridUpdateRoute: GridUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
